name: Build and Publish JAR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build distribution ZIP with dependencies
        run: ./gradlew distWithDeps

      - name: Run tests and generate coverage report
        run: ./gradlew test

      - name: Upload distribution ZIP
        uses: actions/upload-artifact@v4
        with:
          name: kafka-connect-custom-transforms-dist
          path: build/distributions/*.zip

